"""empty message

Revision ID: 358b97de93d0
Revises: ed4ee3884226
Create Date: 2022-05-31 15:56:00.886339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '358b97de93d0'
down_revision = 'ed4ee3884226'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wins', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('losses', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('losses')
        batch_op.drop_column('wins')

    # ### end Alembic commands ###
